Controllers/FirestoreController.cs
using DemoDPGJobData.Models;
using DemoDPGJobData.ViewModels;
using Google.Cloud.Firestore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

public class FirestoreController : Controller
{
    private readonly FirestoreDb _firestoreDb;
    private readonly ILogger<FirestoreController> _logger;

    public FirestoreController(FirestoreDb firestoreDb, ILogger<FirestoreController> logger){
        _firestoreDb = firestoreDb;
        _logger = logger;
    }

    /// <summary>
    /// View all the data in the Firestore database
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult>ViewAllData(){
        CollectionReference collection = _firestoreDb.Collection("DemoJobData");
        QuerySnapshot snapshot = await collection.GetSnapshotAsync();
        var documents = snapshot.Documents.Select(d => d.ConvertTo<DemoJobData>()).ToList();

        CollectionReference collection2 = _firestoreDb.Collection("JobOp");
        QuerySnapshot snapshot2 = await collection2.GetSnapshotAsync();
        var operations = snapshot2.Documents.Select(d => d.ConvertTo<JobOp>()).ToList();

        var result = from d in documents 
                        join o in operations on d.JobOpId equals o.Id
                        select new JobDataViewModel
                            {
                                DemoJobData = d,
                                JobOp = o
                            };
                            

        return View(result.ToList().AsEnumerable());   
    }

    /// <summary>
    /// Present the view for entering new Data
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult> AddData(){
        CollectionReference collection = _firestoreDb.Collection("JobOp");
        QuerySnapshot snapshot = await collection.GetSnapshotAsync();
        var operations = snapshot.Documents.Select(d => d.ConvertTo<JobOp>()).ToList();
        ViewData["JobOps"] = new SelectList(operations, "Id", "OpName");

        return View();
    }

    /// <summary>
    /// Add the new data to the database collection named "DemoJobData"
    /// </summary>
    /// <param name="demoJobData"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<IActionResult>AddData(JobDataViewModel model)
    {
        model.DemoJobData.JobDataId = Guid.NewGuid().ToString();

        DateTime utcDate = model.DemoJobData.DateToday.Date.ToUniversalTime();

        DateTime dateTime1 = DateTime.ParseExact(model.DemoJobData.StartTime, "HH:mm", null);
        DateTime dateTime2 = DateTime.ParseExact(model.DemoJobData.EndTime, "HH:mm", null);
        TimeSpan difference = dateTime2 - dateTime1;
        
        CollectionReference collection = _firestoreDb.Collection("DemoJobData");
        DocumentReference document = await collection.AddAsync(new DemoJobData
        {
            JobDataId = model.DemoJobData.JobDataId,
            Initials= model.DemoJobData.Initials,
            JobNum = model.DemoJobData.JobNum,
            StartTime = model.DemoJobData.StartTime,
            EndTime = model.DemoJobData.EndTime,
            Quantity = model.DemoJobData.Quantity,
            DateToday = utcDate,
            Minutes = difference.TotalMinutes,
            JobOp = model.JobOp,
            JobOpId = model.JobOp.Id
        });
        return RedirectToAction("AddData");
    }

    /// <summary>
    /// Edit the data in the Firestore database
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult>EditData(string id)
    {
        CollectionReference collection = _firestoreDb.Collection("DemoJobData");
        QuerySnapshot snapshot = await collection.GetSnapshotAsync();
        var documents = snapshot.Documents.Select(d => d.ConvertTo<DemoJobData>()).ToList();

        CollectionReference collection2 = _firestoreDb.Collection("JobOp");
        QuerySnapshot snapshot2 = await collection2.GetSnapshotAsync();
        var operations = snapshot2.Documents.Select(d => d.ConvertTo<JobOp>()).ToList();
       ViewData["JobOps"] = new SelectList(operations, "Id", "OpName");

        var result = from d in documents 
                        join o in operations on d.JobOpId equals o.Id
                        where d.JobDataId == id
                        select new JobDataViewModel
                            {
                                DemoJobData = d,
                                JobOp = o
                            };

        var specificDocumentModel = result.FirstOrDefault();

        return View(specificDocumentModel);   
    }

    /// <summary>
    /// Edit a document in the database collection named "DemoJobData"
    /// </summary>
    /// <param name="demoJobData"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<IActionResult>EditData(JobDataViewModel model)
    {
        var jobDataId = model.DemoJobData.JobDataId ?? Guid.NewGuid().ToString(); // coalesce expression checking for null
        DateTime utcDate = model.DemoJobData.DateToday.Date.ToUniversalTime();

        DateTime dateTime1 = DateTime.ParseExact(model.DemoJobData.StartTime, "HH:mm", null);
        DateTime dateTime2 = DateTime.ParseExact(model.DemoJobData.EndTime, "HH:mm", null);
        TimeSpan difference = dateTime2 - dateTime1;
        
        var collection = _firestoreDb.Collection("DemoJobData");
        var query = collection.WhereEqualTo("JobDataId", model.DemoJobData.JobDataId);
        var snapshot = await query.GetSnapshotAsync();

        if(!snapshot.Documents.Any())
        {
            _logger.LogError("Document not found with JobDataID: {JobDataId}", model.DemoJobData.JobDataId);
            return NotFound();
        }

        var documentReference = snapshot.Documents[0].Reference;


        var updateData = new Dictionary<string, object>
        {
            {"JobDataId", jobDataId},
            {"Initials", model.DemoJobData.Initials},
            {"JobNum", model.DemoJobData.JobNum},
            {"StartTime", model.DemoJobData.StartTime},
            {"EndTime", model.DemoJobData.EndTime},
            {"Quantity", model.DemoJobData.Quantity},
            {"DateToday", utcDate},
            {"Minutes", difference.TotalMinutes},
            {"JobOpId", model.JobOp.Id}
        };

        await documentReference.SetAsync(updateData);

        return RedirectToAction("ViewAllData");
    }

    /// <summary>
    /// Delete specific data document in the Firestore database
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult>DeleteData(string id)
    {
        CollectionReference collection = _firestoreDb.Collection("DemoJobData");
        QuerySnapshot snapshot = await collection.GetSnapshotAsync();
        var documents = snapshot.Documents.Select(d => d.ConvertTo<DemoJobData>()).ToList();

        CollectionReference collection2 = _firestoreDb.Collection("JobOp");
        QuerySnapshot snapshot2 = await collection2.GetSnapshotAsync();
        var operations = snapshot2.Documents.Select(d => d.ConvertTo<JobOp>()).ToList();
       ViewData["JobOps"] = new SelectList(operations, "Id", "OpName");

        var result = from d in documents 
                        join o in operations on d.JobOpId equals o.Id
                        where d.JobDataId == id
                        select new JobDataViewModel
                            {
                                DemoJobData = d,
                                JobOp = o
                            };

        var specificDocumentModel = result.FirstOrDefault();

        return View(specificDocumentModel);   
    }

    /// <summary>
    /// Delete specific data document in the Firestore database
    /// </summary>
    /// <returns></returns>
    [HttpPost]
    public async Task<IActionResult>DeleteData(JobDataViewModel model)
    {
        var id = model.DemoJobData.JobDataId;

        if(string.IsNullOrEmpty(id))
        {
            _logger.LogError("Invalid document ID");
            return BadRequest("Invalid document ID");
        }

        var collection = _firestoreDb.Collection("DemoJobData");
        var query = collection.WhereEqualTo("JobDataId",id);
        var snapshot = await query.GetSnapshotAsync();

        if(!snapshot.Documents.Any())
        {
            _logger.LogError("Document not found: {JobDataId}", id);
            return NotFound();
        }

        var documentReference = snapshot.Documents.First().Reference;
        await documentReference.DeleteAsync();
        _logger.LogInformation("Document deleted: {DocumentId}", id);
        
        return RedirectToAction("ViewAllData");
    }


}

Views/Firestore/AddData.cshtml
@model DemoDPGJobData.ViewModels.JobDataViewModel;

@{
    ViewData["Title"] = "Add Data";
}

<div class="container">

<h2>Add Data to Firestore</h2>

<form asp-action="AddData" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.Initials" class="control-label">Initials</label>
            <input asp-for="DemoJobData.Initials" 
                class="form-control" maxlength="2" required
                placeholder="Example:  CP" />
            <span asp-validation-for="DemoJobData.Initials" class="text-danger"></span>
        </div>
        <div class="col-sm-6 mb-3">
            <label class="mr-1" style="padding-right: 1em">Today's Date:</label>
            <input class="form-control" placeholder="Please select the date" 
                type="date" 
                asp-for="DemoJobData.DateToday" 
                name="DemoJobData.DateToday"/>
            <span asp-validation-for="DemoJobData.DateToday" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.JobNum" class="control-label">Job Number</label>
            <input asp-for="DemoJobData.JobNum" 
                class="form-control" maxlength="5" required
                placeholder="Example:  12345" />
            <span asp-validation-for="DemoJobData.JobNum" class="text-danger"></span>
        </div>
        <div class="col-sm-6 mb-3">
            <label  class="control-label" asp-for="JobOp.Id">Select Operation</label>
            <select class="form-select" asp-for="JobOp.Id" asp-items="ViewBag.JobOps" required></select>
            <span asp-validation-for="JobOp.Id" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.StartTime" class="control-label">Start Time</label>
            <input 
                type="time"
                asp-for="DemoJobData.StartTime"
                name="DemoJobData.StartTime" 
                class="form-control" maxlength="12" required/>
            <span asp-validation-for="DemoJobData.StartTime" class="text-danger"></span>
        </div>
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.EndTime" class="control-label">End Time</label>
            <input 
                type="time"
                asp-for="DemoJobData.EndTime"
                name="DemoJobData.EndTime" 
                class="form-control" maxlength="12" required/>
            <span asp-validation-for="DemoJobData.EndTime" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.Quantity" class="control-label">Quantity</label>
            <input asp-for="DemoJobData.Quantity" 
                class="form-control" maxlength="4" required
                placeholder="Example:  400" />
            <span asp-validation-for="DemoJobData.Quantity" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="form-group mb-3">
            <a asp-controller="Firestore" asp-action="AddData" class="btn btn-outline-danger">Clear Form</a>
            <input type="submit" value="Add Data" class="btn btn-primary" />
        </div>
    </div>

</form>

<div>
    <a asp-controller="Firestore" asp-action="ViewAllData">Back to List</a>
</div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Firestore/DeleteData.cshtml
@model DemoDPGJobData.ViewModels.JobDataViewModel;

@{
    ViewData["Title"] = "Delete Data";
}

<div class="container">

<h2>Delete Data in Firestore</h2>

<form asp-action="DeleteData" method="post">
        <input type="hidden" asp-for="DemoJobData.JobDataId" value="@Model.DemoJobData.JobDataId" readonly/>

    <div class="row">
        <div class="col-sm-4 mb-3">
            <label asp-for="DemoJobData.JobNum" class="control-label">Job Number</label>
            <input type="text" asp-for="DemoJobData.JobNum" 
                class="form-control"/>
        </div>
        <div class="col-sm-4 mb-3">
            <label asp-for="DemoJobData.Initials" class="control-label">Initials</label>
            <input asp-for="DemoJobData.Initials" 
                class="form-control" />
        </div>
        <div class="col-sm-4 mb-3">
            <label class="mr-1" style="padding-right: 1em">Date:</label>
            <input class="form-control" 
                type="date" 
                asp-for="DemoJobData.DateToday" 
                name="DemoJobData.DateToday"/>
        </div>
    </div>

    <div class="form-group" style="display: none;">
        <label asp-for="DemoJobData.JobDataId">Document ID</label>
        <input type="text" asp-for="DemoJobData.JobDataId" class="form-control"/>
    </div>

    <div class="row mb-3">
        <div class="form-group">
            <a asp-controller="Firestore" asp-action="ViewAllData" class="btn btn-outline-danger">Discard Changes</a>
        <button type="submit" class="btn btn-danger">Delete</button>
        </div>
    </div>


</form>

</div>

Views/Firestore/EditData.cshtml
@model DemoDPGJobData.ViewModels.JobDataViewModel;

@{
    ViewData["Title"] = "Edit Data";
}

<div class="container">

<h2>Edit Data in Firestore</h2>

<form asp-action="EditData" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="DemoJobData.JobDataId" value="@Model.DemoJobData.JobDataId" readonly/>
    <div class="row">
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.Initials" class="control-label">Initials</label>
            <input asp-for="DemoJobData.Initials" 
                class="form-control" maxlength="2" required/>
            <span asp-validation-for="DemoJobData.Initials" class="text-danger"></span>
        </div>
        <div class="col-sm-6 mb-3">
            <label class="mr-1" style="padding-right: 1em">Date:</label>
            <input class="form-control" 
                type="date" 
                asp-for="DemoJobData.DateToday" 
                name="DemoJobData.DateToday"/>
            <span asp-validation-for="DemoJobData.DateToday" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.JobNum" class="control-label">Job Number</label>
            <input asp-for="DemoJobData.JobNum" 
                class="form-control" maxlength="5" required/>
            <span asp-validation-for="DemoJobData.JobNum" class="text-danger"></span>
        </div>
        <div class="col-sm-6 mb-3">
            <label  class="control-label" asp-for="JobOp.Id">Operation</label>
            <select class="form-select" asp-for="JobOp.Id" asp-items="ViewBag.JobOps" 
                    required>
                    <option value="0" selected></option></select>
            <span asp-validation-for="JobOp.Id" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.StartTime" class="control-label">Start Time</label>
            <input 
                type="time"
                asp-for="DemoJobData.StartTime"
                name="DemoJobData.StartTime" 
                class="form-control" maxlength="12" required/>
            <span asp-validation-for="DemoJobData.StartTime" class="text-danger"></span>
        </div>
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.EndTime" class="control-label">End Time</label>
            <input 
                type="time"
                asp-for="DemoJobData.EndTime"
                name="DemoJobData.EndTime" 
                class="form-control" maxlength="12" required/>
            <span asp-validation-for="DemoJobData.EndTime" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 mb-3">
            <label asp-for="DemoJobData.Quantity" class="control-label">Quantity</label>
            <input asp-for="DemoJobData.Quantity" 
                class="form-control" maxlength="4" required/>
            <span asp-validation-for="DemoJobData.Quantity" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-3">
        <div class="form-group">
            <a asp-controller="Firestore" asp-action="ViewAllData" class="btn btn-outline-danger">Discard Changes</a>
            <input type="submit" value="Save Changes" class="btn btn-primary ml-3" />
        </div>
    </div>

</form>


<div>
    <a asp-controller="Firestore" asp-action="ViewAllData">Back to List</a>
</div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Firestore/ViewAllData.cshtml
@model IEnumerable<DemoDPGJobData.ViewModels.JobDataViewModel>

@{
    ViewData["Title"] = "View Data";
}

<div class="container">

<h2>View Firestore Data</h2>

<table class="stripe nowrap" id="viewDataTable">
    <thead>
        <tr>
            <th>Date</th>
            <th>Initials</th>
            <th>Job Number</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Minutes</th>
            <th>Quantity</th>
            <th>Operation</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model){
            <tr>
                <td>@item.DemoJobData.DateToday.ToString("dd/MM/yyyy")</td>
                <td>@item.DemoJobData.Initials</td>
                <td>@item.DemoJobData.JobNum</td>
                <td>@item.DemoJobData.StartTime</td>
                <td>@item.DemoJobData.EndTime</td>
                <td>@item.DemoJobData.Minutes</td>
                <td>@item.DemoJobData.Quantity</td>
                <td>@item.JobOp.OpName</td>
                <td>
                    <a class="btn btn-primary" asp-controller="Firestore" asp-action="EditData" asp-route-id="@item.DemoJobData.JobDataId">Edit</a>
                    <a class="btn btn-danger" asp-controller="Firestore" asp-action="DeleteData" asp-route-id="@item.DemoJobData.JobDataId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-controller="Home" asp-action="Index">Back to Home Page</a>
</div>

</div>


<link href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css" rel="stylesheet" />

@section scripts{
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
    <script>
        // Creates DataTable
        // DataTable Documentation found here: https://datatables.net/
        $(function () {
            $('#viewDataTable').DataTable({
                columns: [null,null,null,null,null,null,null,null, { orderable: false }],
                order: [[0, 'asc']],
                @* pageLength: 10,
                searching: true,
                lengthChange: false,
                language: {
                    emptyTable: 'No data found'
                } *@
            });
        });
    </script>
}